
name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install pylint
#        pip install --no-cache-dir -r requeriments.txt
#    - name: Analysing the code with pylint
#      run: |
#        pylint `ls -R|grep .py$|xargs`
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag flexomeno/flaskapi
      
    - name: Docker Push
      run: docker push flexomeno/flaskapi